name: Build and push Docker image

on:
  workflow_call:
    inputs:
      image_name:
        description: The name of the docker image to use
        required: true
        type: string
      context:
        description: The path for the docker build context, defaults to '.'
        required: false
        type: string
        default: .
      file:
        description: Path to the Dockerfile. (default ./Dockerfile)
        required: false
        type: string
        default: ./Dockerfile
      build_args:
        description: Additional Docker build arguments (one per line)
        required: false
        type: string
      create_prerelease:
        description: Whether to create a pre-release in GitHub for this image
        required: false
        type: boolean
        default: true
    outputs:
      image_tag:
        description: The tag of the docker image to use
        value: ${{ jobs.build_and_push_image.outputs.image_tag }}

permissions:
  contents: write
  deployments: write
  packages: write
  id-token: write
  pull-requests: read
  attestations: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/${{ inputs.image_name }}
  IS_PULL_REQUEST_TRIGGERED: ${{ github.event_name == 'pull_request' }}

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.image_tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Find associated pull request
        uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@actions/v1
        id: find_pull_request

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Declare Docker image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Determine image tag
        id: image_tag
        run: echo "tag=pr${{ steps.find_pull_request.outputs.pull_request_number }}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        id: push_image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          cache-from: type=gha
          cache-to: type=gha
          push: true
          tags: ${{ steps.image_name.outputs.lowercase }}:${{ steps.image_tag.outputs.tag }}
          build-args: |
            SourceRevisionId=PR_${{ steps.find_pull_request.outputs.pull_request_number }}+SHA_${{ github.sha }}
            ${{ inputs.build_args }}

      - name: Generate SBOM from image
        id: generate_sbom_image
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.image_name.outputs.lowercase }}:${{ steps.image_tag.outputs.tag }}
          format: spdx-json
          output-file: sbom.spdx.json
          artifact-name: sbom-${{ inputs.image_name }}.spdx.json

      - name: Attest SBOM
        uses: actions/attest-sbom@v3
        continue-on-error: true # We might hit limits on attestations, for now we skip if it happens as we want to move to ACR
        with:
          subject-name: ${{ steps.image_name.outputs.lowercase }}
          subject-digest: ${{ steps.push_image.outputs.digest }}
          sbom-path: sbom.spdx.json
          push-to-registry: true

      - name: Create pre-release
        if: ${{ inputs.create_prerelease && (github.event_name == 'pull_request' || github.event_name == 'merge_group') }}
        uses: Energinet-DataHub/.github/.github/actions/github-create-release@actions/v1
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: ${{ inputs.image_name }}_${{ steps.find_pull_request.outputs.pull_request_number }}
          prerelease: true
          title: ${{ inputs.image_name }}_${{ steps.find_pull_request.outputs.pull_request_number }}
          files: README.md
